/*
 * Object Oriented Programming Principles
 * End of Semester class project
 * 
 */
package Project;

/**
 *
 * @author 101794
 */
public class HomeView extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public HomeView() {
        initComponents();
        if(Utils.loggedIn) {
            welcomeLabel.setText("Welcome "+Utils.user.getFullname());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        welcomeLabel = new javax.swing.JLabel();
        dashLabel = new javax.swing.JLabel();
        mainTabbedPane = new javax.swing.JTabbedPane();
        projectPanel = new javax.swing.JPanel();
        projectHeaderLabel = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        sponsorLabel = new javax.swing.JLabel();
        pmLabel = new javax.swing.JLabel();
        activitiesLabel = new javax.swing.JLabel();
        titleTxt = new javax.swing.JTextField();
        sponsorTxt = new javax.swing.JTextField();
        pmTxt = new javax.swing.JTextField();
        addProjectBtn = new javax.swing.JButton();
        projectsScrollPane = new javax.swing.JScrollPane();
        projectsTable = new javax.swing.JTable();
        updateProjectBtn = new javax.swing.JButton();
        deleteProjectBtn = new javax.swing.JButton();
        budgetLabel = new javax.swing.JLabel();
        costLabel = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        personelLabel = new javax.swing.JLabel();
        progressLabel = new javax.swing.JLabel();
        progressTxt = new javax.swing.JComboBox<>();
        activitiesTxt = new javax.swing.JFormattedTextField();
        budgetTxt = new javax.swing.JFormattedTextField();
        costTxt = new javax.swing.JFormattedTextField();
        startTxt = new javax.swing.JFormattedTextField();
        personnelTxt = new javax.swing.JFormattedTextField();
        endTxt = new javax.swing.JFormattedTextField();
        disbursePanel = new javax.swing.JPanel();
        countyStatsPanel = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        homeMenuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        projectsMI = new javax.swing.JMenuItem();
        disburseMI = new javax.swing.JMenuItem();
        logoutMI = new javax.swing.JMenuItem();
        accountMenu = new javax.swing.JMenu();
        accountMI = new javax.swing.JMenuItem();
        expensesMI = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMI = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CGIS - County Government Information System");

        dashLabel.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        dashLabel.setText("Dashboard");

        projectHeaderLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        projectHeaderLabel.setText("Project Details");

        titleLabel.setText("Title");

        sponsorLabel.setText("Project Sponsor");

        pmLabel.setText("Project Manager");

        activitiesLabel.setText("No. of Activities");

        addProjectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/images/icons8-plus-16.png"))); // NOI18N
        addProjectBtn.setText("Add");
        addProjectBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProjectBtnActionPerformed(evt);
            }
        });

        projectsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        projectsScrollPane.setViewportView(projectsTable);

        updateProjectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/images/icons8-update-16.png"))); // NOI18N
        updateProjectBtn.setText("Update");

        deleteProjectBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/images/icons8-trash-16.png"))); // NOI18N
        deleteProjectBtn.setText("Delete");

        budgetLabel.setText("Budget");

        costLabel.setText("Actual Cost");

        startDateLabel.setText("Start Date");

        endDateLabel.setText("End Date");

        personelLabel.setText("Personnel");

        progressLabel.setText("Progress");

        progressTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        activitiesTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        budgetTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        costTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,##0.00"))));

        startTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        startTxt.setToolTipText("Date Format yyyy-MM-dd e.g. 2018-03-23");

        personnelTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));

        endTxt.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        endTxt.setToolTipText("Date Format yyyy-MM-dd e.g. 2018-03-23");

        javax.swing.GroupLayout projectPanelLayout = new javax.swing.GroupLayout(projectPanel);
        projectPanel.setLayout(projectPanelLayout);
        projectPanelLayout.setHorizontalGroup(
            projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(projectHeaderLabel)
                    .addGroup(projectPanelLayout.createSequentialGroup()
                        .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(projectPanelLayout.createSequentialGroup()
                                .addComponent(addProjectBtn)
                                .addGap(18, 18, 18)
                                .addComponent(updateProjectBtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(deleteProjectBtn))
                            .addGroup(projectPanelLayout.createSequentialGroup()
                                .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleLabel)
                                    .addComponent(sponsorLabel)
                                    .addComponent(pmLabel)
                                    .addComponent(activitiesLabel)
                                    .addComponent(budgetLabel)
                                    .addComponent(costLabel)
                                    .addComponent(startDateLabel)
                                    .addComponent(endDateLabel)
                                    .addComponent(personelLabel)
                                    .addComponent(progressLabel))
                                .addGap(35, 35, 35)
                                .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(titleTxt)
                                    .addComponent(sponsorTxt)
                                    .addComponent(pmTxt)
                                    .addComponent(activitiesTxt)
                                    .addComponent(budgetTxt)
                                    .addComponent(costTxt)
                                    .addComponent(startTxt)
                                    .addComponent(personnelTxt)
                                    .addGroup(projectPanelLayout.createSequentialGroup()
                                        .addComponent(progressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(endTxt))))
                        .addGap(18, 18, 18)))
                .addComponent(projectsScrollPane))
        );
        projectPanelLayout.setVerticalGroup(
            projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectPanelLayout.createSequentialGroup()
                .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(projectPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(projectHeaderLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(titleLabel)
                            .addComponent(titleTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sponsorLabel)
                            .addComponent(sponsorTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(13, 13, 13)
                        .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pmLabel)
                            .addComponent(pmTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(activitiesLabel)
                            .addComponent(activitiesTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(budgetLabel)
                            .addComponent(budgetTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(costLabel)
                            .addComponent(costTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(startDateLabel)
                            .addComponent(startTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(endDateLabel)
                            .addComponent(endTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(projectPanelLayout.createSequentialGroup()
                                .addComponent(personelLabel)
                                .addGap(24, 24, 24)
                                .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(progressLabel)
                                    .addComponent(progressTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(projectPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(addProjectBtn)
                                    .addComponent(updateProjectBtn)
                                    .addComponent(deleteProjectBtn)))
                            .addGroup(projectPanelLayout.createSequentialGroup()
                                .addComponent(personnelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(projectsScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainTabbedPane.addTab("Projects ", new javax.swing.ImageIcon(getClass().getResource("/Project/images/icons8-project-50.png")), projectPanel); // NOI18N

        javax.swing.GroupLayout disbursePanelLayout = new javax.swing.GroupLayout(disbursePanel);
        disbursePanel.setLayout(disbursePanelLayout);
        disbursePanelLayout.setHorizontalGroup(
            disbursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );
        disbursePanelLayout.setVerticalGroup(
            disbursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("Disbursements ", new javax.swing.ImageIcon(getClass().getResource("/Project/images/icons8-cash-in-hand-50.png")), disbursePanel); // NOI18N

        javax.swing.GroupLayout countyStatsPanelLayout = new javax.swing.GroupLayout(countyStatsPanel);
        countyStatsPanel.setLayout(countyStatsPanelLayout);
        countyStatsPanelLayout.setHorizontalGroup(
            countyStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );
        countyStatsPanelLayout.setVerticalGroup(
            countyStatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );

        mainTabbedPane.addTab("County Stats ", new javax.swing.ImageIcon(getClass().getResource("/Project/images/icons8-statistics-50.png")), countyStatsPanel); // NOI18N

        fileMenu.setText("File");

        projectsMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/images/icons8-project-50.png"))); // NOI18N
        projectsMI.setText("Projects");
        projectsMI.setToolTipText("Manage Projects");
        fileMenu.add(projectsMI);

        disburseMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/images/icons8-cash-in-hand-50.png"))); // NOI18N
        disburseMI.setText("Disbursements");
        disburseMI.setToolTipText("Manage Fund Disbursements");
        fileMenu.add(disburseMI);

        logoutMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        logoutMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/images/icons8-logout-rounded-left-50.png"))); // NOI18N
        logoutMI.setText("Logout");
        logoutMI.setToolTipText("Logout");
        logoutMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMIActionPerformed(evt);
            }
        });
        fileMenu.add(logoutMI);

        homeMenuBar.add(fileMenu);

        accountMenu.setText("Profile");

        accountMI.setText("My Account");
        accountMenu.add(accountMI);

        expensesMI.setText("My Expenses");
        accountMenu.add(expensesMI);

        homeMenuBar.add(accountMenu);

        helpMenu.setText("Help");

        aboutMI.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        aboutMI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Project/images/icons8-help-50.png"))); // NOI18N
        aboutMI.setText("About CGIS");
        aboutMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutMIActionPerformed(evt);
            }
        });
        helpMenu.add(aboutMI);

        homeMenuBar.add(helpMenu);

        setJMenuBar(homeMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainTabbedPane)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(welcomeLabel)
                            .addComponent(dashLabel))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statusLabel)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(welcomeLabel)
                .addGap(18, 18, 18)
                .addComponent(dashLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 577, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMIActionPerformed
        if(Utils.showDialog("Are you sure you want to logout?") == 0) {
            // logout user...Close Main App and show the login form
            Utils.logout();
            java.awt.EventQueue.invokeLater(() -> {
                new LoginView().setVisible(true);
            });
            this.dispose();
        }
    }//GEN-LAST:event_logoutMIActionPerformed

    private void aboutMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutMIActionPerformed
        // Show about this project
        
    }//GEN-LAST:event_aboutMIActionPerformed

    private void addProjectBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProjectBtnActionPerformed
        // Add a new project
        if (dataValid("project")) {
            
        }
    }//GEN-LAST:event_addProjectBtnActionPerformed

    private boolean dataValid(String type) {
        if("project".equals(type)) {
            int user_id = Utils.user.getID();
            int county_id = Utils.user.getCountyID();
            String title = titleTxt.getText().trim();
            String sponsor = sponsorTxt.getText().trim();
            String pm = pmTxt.getText().trim();
            int activities = Integer.parseInt(activitiesTxt.getText().trim());
        } else if ("disburse".equals(type)) {
            
        }
        
        return true;
    }
    
    /**
     * @param args the command line arguments
     *
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         *
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form *
        java.awt.EventQueue.invokeLater(() -> {
            new HomeView().setVisible(true);
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMI;
    private javax.swing.JMenuItem accountMI;
    private javax.swing.JMenu accountMenu;
    private javax.swing.JLabel activitiesLabel;
    private javax.swing.JFormattedTextField activitiesTxt;
    private javax.swing.JButton addProjectBtn;
    private javax.swing.JLabel budgetLabel;
    private javax.swing.JFormattedTextField budgetTxt;
    private javax.swing.JLabel costLabel;
    private javax.swing.JFormattedTextField costTxt;
    private javax.swing.JPanel countyStatsPanel;
    private javax.swing.JLabel dashLabel;
    private javax.swing.JButton deleteProjectBtn;
    private javax.swing.JMenuItem disburseMI;
    private javax.swing.JPanel disbursePanel;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JFormattedTextField endTxt;
    private javax.swing.JMenuItem expensesMI;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar homeMenuBar;
    private javax.swing.JMenuItem logoutMI;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JLabel personelLabel;
    private javax.swing.JFormattedTextField personnelTxt;
    private javax.swing.JLabel pmLabel;
    private javax.swing.JTextField pmTxt;
    private javax.swing.JLabel progressLabel;
    private javax.swing.JComboBox<String> progressTxt;
    private javax.swing.JLabel projectHeaderLabel;
    private javax.swing.JPanel projectPanel;
    private javax.swing.JMenuItem projectsMI;
    private javax.swing.JScrollPane projectsScrollPane;
    private javax.swing.JTable projectsTable;
    private javax.swing.JLabel sponsorLabel;
    private javax.swing.JTextField sponsorTxt;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JFormattedTextField startTxt;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField titleTxt;
    private javax.swing.JButton updateProjectBtn;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
